[project]
name = "entregas-lab-engsoftware"
version = "0.1.0"
description = "Backend do projeto BookStore"
readme = "README.md"
authors = [
    { name = "Wesley Xavier", email = "wesley.xvier@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "sqlalchemy>=2.0.52",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
