from src.domain.entities import Book
from src.domain.repositories import BookRepository

NATIVE_BOOKS: list[dict] = [
    {
        "isbn": "9788593828966",
        "title": "O Cortiço",
        "authors": ["Aluísio Azevedo"],
        "publisher": "Todavia",
        "genre": ["Romance", "Clássico"],
        "theme": ["Naturalismo", "Sociedade"],
    },
    {
        "isbn": "9788520912096",
        "title": "Grande Sertão: Veredas",
        "authors": ["João Guimarães Rosa"],
        "publisher": "Nova Fronteira",
        "genre": ["Romance", "Clássico"],
        "theme": ["Sertão", "Amor"],
    },
    {
        "isbn": "9788501114778",
        "title": "Vidas Secas",
        "authors": ["Graciliano Ramos"],
        "publisher": "Record",
        "genre": ["Romance", "Clássico"],
        "theme": ["Seca", "Sobrevivência"],
    },
    {
        "isbn": "9788532530660",
        "title": "A Hora da Estrela",
        "authors": ["Clarice Lispector"],
        "publisher": "Rocco",
        "genre": ["Romance", "Clássico"],
        "theme": ["Solidão", "Identidade"],
    },
    {
        "isbn": "9786559570737",
        "title": "O Pequeno Príncipe",
        "authors": ["Antoine de Saint-Exupéry"],
        "publisher": "Prime",
        "genre": ["Fábula", "Infantojuvenil"],
        "theme": ["Amizade", "Infância"],
    },
    {
        "isbn": "9786555790641",
        "title": "A Revolução dos Bichos",
        "authors": ["George Orwell"],
        "publisher": "PandorgA",
        "genre": ["Sátira", "Distopia"],
        "theme": ["Poder", "Política"],
    },
    {
        "isbn": "9788525033222",
        "title": "Admirável Mundo Novo",
        "authors": ["Aldous Huxley"],
        "publisher": "Globo",
        "genre": ["Ficção Científica", "Distopia"],
        "theme": ["Tecnologia", "Liberdade"],
    },
    {
        "isbn": "9788533615540",
        "title": "O Hobbit",
        "authors": ["J.R.R. Tolkien"],
        "publisher": "WMF Martins Fontes",
        "genre": ["Fantasia", "Aventura"],
        "theme": ["Jornada", "Coragem"],
    },
    {
        "isbn": "9788573266467",
        "title": "Crime e Castigo",
        "authors": ["Fiódor Dostoiévski"],
        "publisher": "Editora 34",
        "genre": ["Romance", "Clássico"],
        "theme": ["Culpa", "Moral"],
    },
    {
        "isbn": "9780374523039",
        "title": "Dom Casmurro",
        "authors": ["Machado de Assis"],
        "publisher": "Noonday Press",
        "genre": ["Romance", "Clássico"],
        "theme": ["Ciúme", "Memória"],
    },
    {
        "isbn": "9780451524935",
        "title": "1984",
        "authors": ["George Orwell"],
        "publisher": "Signet Classics",
        "genre": ["Ficção Científica", "Distopia"],
        "theme": ["Vigilância", "Totalitarismo"],
    },
    {
        "isbn": "9780590353427",
        "title": "Harry Potter and the Sorcerer's Stone",
        "authors": ["J.K. Rowling"],
        "publisher": "Scholastic",
        "genre": ["Fantasia", "Infantojuvenil"],
        "theme": ["Magia", "Amizade"],
    },
    {
        "isbn": "9780141439518",
        "title": "Pride and Prejudice",
        "authors": ["Jane Austen"],
        "publisher": "Penguin Books",
        "genre": ["Romance", "Clássico"],
        "theme": ["Sociedade", "Amor"],
    },
    {
        "isbn": "9780061120084",
        "title": "To Kill a Mockingbird",
        "authors": ["Harper Lee"],
        "publisher": "Harper Perennial Modern Classics",
        "genre": ["Romance", "Clássico"],
        "theme": ["Justiça", "Preconceito"],
    },
    {
        "isbn": "9780618346257",
        "title": "The Fellowship of the Ring",
        "authors": ["J.R.R. Tolkien"],
        "publisher": "Houghton Mifflin",
        "genre": ["Fantasia", "Aventura"],
        "theme": ["Jornada", "Amizade"],
    },
    {
        "isbn": "9781471141638",
        "title": "Wuthering Heights",
        "authors": ["Emily Brontë"],
        "publisher": "Simon & Schuster",
        "genre": ["Romance", "Clássico"],
        "theme": ["Obsessão", "Vingança"],
    },
    {
        "isbn": "9780441013593",
        "title": "Dune",
        "authors": ["Frank Herbert"],
        "publisher": "Ace Books",
        "genre": ["Ficção Científica", "Aventura"],
        "theme": ["Poder", "Ecologia"],
    },
    {
        "isbn": "9780385611466",
        "title": "The Book Thief",
        "authors": ["Markus Zusak"],
        "publisher": "Doubleday",
        "genre": ["Ficção Histórica", "Juvenil"],
        "theme": ["Guerra", "Leitura"],
    },
    {
        "isbn": "9781451673319",
        "title": "Fahrenheit 451",
        "authors": ["Ray Bradbury"],
        "publisher": "Simon & Schuster Paperbacks",
        "genre": ["Ficção Científica", "Distopia"],
        "theme": ["Censura", "Livros"],
    },
    {
        "isbn": "9780316769488",
        "title": "The Catcher in the Rye",
        "authors": ["J.D. Salinger"],
        "publisher": "Little, Brown and Company",
        "genre": ["Romance", "Clássico"],
        "theme": ["Adolescência", "Solidão"],
    },
    {
        "isbn": "9781423796053",
        "title": "Frankenstein",
        "authors": ["Mary Shelley"],
        "publisher": "ICON Classics",
        "genre": ["Terror", "Clássico"],
        "theme": ["Ciência", "Criação"],
    },
    {
        "isbn": "9781569319017",
        "title": "One Piece, Vol. 1: Romance Dawn",
        "authors": ["Eiichiro Oda"],
        "publisher": "Shonen Jump",
        "genre": ["Mangá", "Aventura", "Shounen"],
        "theme": ["Piratas", "Amizade"],
    },
    {
        "isbn": "9781421501680",
        "title": "Death Note, Vol. 1",
        "authors": ["Tsugumi Ohba", "Takeshi Obata"],
        "publisher": "Viz Media",
        "genre": ["Mangá", "Suspense", "Sobrenatural"],
        "theme": ["Justiça", "Moral"],
    },
    {
        "isbn": "9781569319000",
        "title": "Naruto, Vol. 1",
        "authors": ["Masashi Kishimoto"],
        "publisher": "Viz Media",
        "genre": ["Mangá", "Ação", "Shounen"],
        "theme": ["Ninjas", "Superação"],
    },
    {
        "isbn": "9781421541952",
        "title": "Fullmetal Alchemist Complete Box Set",
        "authors": ["Hiromu Arakawa"],
        "publisher": "Viz Media",
        "genre": ["Mangá", "Aventura", "Fantasia"],
        "theme": ["Alquimia", "Família"],
    },
    {
        "isbn": "9781506711980",
        "title": "Berserk Deluxe Edition, Vol. 1",
        "authors": ["Kentaro Miura"],
        "publisher": "Dark Horse Manga",
        "genre": ["Mangá", "Seinen", "Fantasia"],
        "theme": ["Sobrevivência", "Destino"],
    },
    {
        "isbn": "9781935429005",
        "title": "Akira, Vol. 1",
        "authors": ["Katsuhiro Otomo"],
        "publisher": "Kodansha Comics",
        "genre": ["Mangá", "Ficção Científica", "Seinen"],
        "theme": ["Distopia", "Poder"],
    },
    {
        "isbn": "9781612620244",
        "title": "Attack on Titan, Vol. 1",
        "authors": ["Hajime Isayama"],
        "publisher": "Kodansha Comics",
        "genre": ["Mangá", "Ação", "Shounen"],
        "theme": ["Sobrevivência", "Guerra"],
    },
    {
        "isbn": "9781421569062",
        "title": "Monster: The Perfect Edition, Vol. 1",
        "authors": ["Naoki Urasawa"],
        "publisher": "Viz Media",
        "genre": ["Mangá", "Suspense", "Seinen"],
        "theme": ["Moral", "Mistério"],
    },
    {
        "isbn": "9781974710027",
        "title": "Jujutsu Kaisen, Vol. 1",
        "authors": ["Gege Akutami"],
        "publisher": "Viz Media",
        "genre": ["Mangá", "Ação", "Shounen"],
        "theme": ["Maldições", "Amizade"],
    },
    {
        "isbn": "9780972503792",
        "title": "Slam Dunk, Vol. 1",
        "authors": ["Takehiko Inoue"],
        "publisher": "Gutsoon Entertainment",
        "genre": ["Mangá", "Esporte", "Shounen"],
        "theme": ["Basquete", "Superação"],
    },
    {
        "isbn": "9781401245252",
        "title": "Watchmen",
        "authors": ["Alan Moore", "Dave Gibbons"],
        "publisher": "DC Comics",
        "genre": ["Quadrinhos", "Super-heróis", "Ficção Científica"],
        "theme": ["Poder", "Moral"],
    },
    {
        "isbn": "9780679406419",
        "title": "Maus: A Survivor's Tale",
        "authors": ["Art Spiegelman"],
        "publisher": "Random House",
        "genre": ["Quadrinhos", "Biografia", "Histórico"],
        "theme": ["Holocausto", "Memória"],
    },
    {
        "isbn": "9780375714832",
        "title": "The Complete Persepolis",
        "authors": ["Marjane Satrapi"],
        "publisher": "Pantheon Books",
        "genre": ["Quadrinhos", "Biografia"],
        "theme": ["Irã", "Adolescência"],
    },
    {
        "isbn": "9781401284770",
        "title": "The Sandman, Vol. 1: Preludes & Nocturnes",
        "authors": ["Neil Gaiman", "Sam Kieth"],
        "publisher": "Vertigo",
        "genre": ["Quadrinhos", "Fantasia", "Terror"],
        "theme": ["Sonhos", "Mitologia"],
    },
    {
        "isbn": "9781401207922",
        "title": "V for Vendetta",
        "authors": ["Alan Moore", "David Lloyd"],
        "publisher": "DC Comics",
        "genre": ["Quadrinhos", "Distopia"],
        "theme": ["Anarquia", "Política"],
    },
    {
        "isbn": "9781563893421",
        "title": "Batman: The Dark Knight Returns",
        "authors": ["Frank Miller"],
        "publisher": "DC Comics",
        "genre": ["Quadrinhos", "Super-heróis"],
        "theme": ["Justiça", "Envelhecimento"],
    },
    {
        "isbn": "9781401204877",
        "title": "Y: The Last Man, Vol. 5: Ring of Truth",
        "authors": ["Brian K. Vaughan"],
        "publisher": "DC Comics",
        "genre": ["Quadrinhos", "Ficção Científica"],
        "theme": ["Sobrevivência", "Sociedade"],
    },
    {
        "isbn": "9788532531520",
        "title": "O Conto da Aia: Graphic Novel",
        "authors": ["Margaret Atwood"],
        "publisher": "Rocco",
        "genre": ["Quadrinhos", "Distopia"],
        "theme": ["Opressão", "Resistência"],
    },
]


async def seed_native_catalog(repository: BookRepository) -> int:
    added = 0
    for item in NATIVE_BOOKS:
        if await repository.get_by_isbn(item["isbn"]) is None:
            await repository.save(Book(**item))
            added += 1
    return added
